////////////////////////////////////////////////////////////////////////////
//
//   MMM     MMM       AAA       TTTTTTTTTT  RRRRRR    IIIIIIII  XX   XX
//   MMMM   MMMM      AA AA          TT      RR   RR      II      XX XX
//   MM MM MM MM     AA   AA         TT      RR    RR     II       XXX
//   MM  MM   MM    AAAAAAAAA        TT      RRRRRRR      II       XXX
//   MM       MM   AA       AA       TT      RR  RR       II      XX XX
//   MM       MM  AA         AA      TT      RR   RR   IIIIIIII  XX   XX
//
//   Company      : Matrix ComSec Pvt. Ltd., Baroda, India.
//   Project      : Access Control System
//   Created By   : Manish Chandra
//   File         : MxConfigTableParaStr.c
//   Description  : This file consist of Configuration File I/O related Parameter string.
//
///////////////////////////////////////////////////////////////////////////


//********Place all include files ****
#include "MxTypedef.h"
#include "MxConfig.h"
#include "MxConfigDef.h"
#include "MxBlockDevice.h"

//******** Extern Variables **********


//******** Defines and Data Types ****

//******** Function Prototypes *******

//******** Global Variables **********
// For logging status of reader in response message
const CHARPTR ActiveInactiveStr[MAX_BOOL_ENUM] =
{
	"INACTIVE",
	"ACTIVE",
};

const CHARPTR JobTypeStr[MAX_JCM_TYPE] =
{
	"NONE",
	"FIXED",
	"DEVICE BASED",
};

const CHARPTR InputPortStr[MAX_INPUT_PORT] =
{
	GENERATE_INPUT_PORT(GENERATE_ENUM_STR)
};

const CHARPTR OutputPortStr[MAX_OUTPUT_PORT] =
{
	GENERATE_OUTPUT_PORT(GENERATE_ENUM_STR)
};

const CHARPTR OutputTypeStr[MAX_OUTPUT_TYPE] =
{
	GENERATE_OUTPUT_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR DstStateStr[MAX_DST_STATE] =
{
	GENERATE_DST_STATE(GENERATE_ENUM_STR)
};

const CHARPTR BlockedUserStr[MAX_BLOCK_REASON] =
{
	GENERATE_BLOCK_REASON(GENERATE_ENUM_STR)
};

const CHARPTR DstModeStr[MAX_DST_MODE] =
{
	GENERATE_DST_MODE(GENERATE_ENUM_STR)
};

const CHARPTR WeekOrdinalStr[MAX_WEEKORDINAL] =
{
	GENERATE_WEEKORDINAL(GENERATE_ENUM_STR)
};

const CHARPTR WeekDaysStr[MAX_WDAY] =
{
	GENERATE_WEEKDAYS(GENERATE_ENUM_STR)
};

const CHARPTR MonthStr[MAX_MONTH] =
{
	GENERATE_MONTH(GENERATE_ENUM_STR)
};

//NOTE:Do not put MAX_PORT
const CHARPTR CommPortStr[] =
{
	GENERATE_COMM_PORT(GENERATE_ENUM_STR)
};

const CHARPTR ServerConnectionStr[MAX_SERVER_CONN] =
{
	GENERATE_SERVER_CONN(GENERATE_ENUM_STR)
};

const CHARPTR IpModeStr[MAX_IP_MODE] =
{
	GENERATE_IP_MODE(GENERATE_ENUM_STR)
};

const CHARPTR SecTypeStr[MAX_SEC_TYPE] =
{
	GENERATE_SEC_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR EncryptionStr[MAX_ENCRYPTION] =
{
	GENERATE_ENCRYPTION(GENERATE_ENUM_STR)
};

const CHARPTR WifiKeyMgmtStr[MAX_KEY_MGMT] =
{
	GENERATE_WIFI_KEY_MGMT(GENERATE_ENUM_STR)
};

const CHARPTR WifiAuthTypeStr[MAX_AUTH_TYPE] =
{
	GENERATE_WIFI_AUTH_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR PeapVersionStr[MAX_PEAP_VER] =
{
	GENERATE_PEAP_VER(GENERATE_ENUM_STR)
};

const CHARPTR InnerAuthStr[MAX_INNER_AUTH] =
{
	GENERATE_INNER_AUTH(GENERATE_ENUM_STR)
};

const CHARPTR ModemTypeStr[MAX_MODEM_TYPE] =
{
	GENERATE_MODEM_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR CafeDiscountStr[CAFE_DISCNT_LEVEL_MAX] =
{
	GENERATE_CAFE_DISCNT_LEVEL(GENERATE_ENUM_STR)
};

const CHARPTR PaymentModeStr[MAX_PAYMENT_MODE] =
{
	GENERATE_USER_PAYMENT_MODE(GENERATE_ENUM_STR)
};

const CHARPTR BlockedForCafeStr[MAX_BLOCK_FOR_CAFE] =
{
	GENERATE_USER_BLOCK_FOR_CAFE(GENERATE_ENUM_STR)
};

const CHARPTR LightconditionStr[MAX_LIGHT_CONDITION] =
{
	GENERATE_LIGHT_CONDITION(GENERATE_ENUM_STR)
};

const CHARPTR SensitivityLevelStr[MAX_SENSITIVITY_LEVEL] =
{
	GENERATE_SENSITIVITY_LEVEL(GENERATE_ENUM_STR)
};

const CHARPTR ImageQualityStr[MAX_IMAGE_QUALITY] =
{
	GENERATE_IMAGE_QUALITY(GENERATE_ENUM_STR)
};

const CHARPTR SecurityLevelStr[MAX_SECURITY_LEVEL] =
{
	GENERATE_SECURITY_LEVEL(GENERATE_ENUM_STR)
};

const CHARPTR FastModeStr[MAX_FAST_MODES] =
{
	GENERATE_FAST_MODE(GENERATE_ENUM_STR)
};

const CHARPTR PrinterTypeStr[MAX_PRINTER] =
{
	GENERATE_PRINTER_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR PrinterCommTypStr[MAX_PRINTER_TYPE] =
{
	GENERATE_PRINTER_COMM_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR DvrConfigEventTypStr[MAX_DVR_CONFIG_EVENT_TYPE] =
{
	GENERATE_DVR_CONFIG_EVENT_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR ReaderModeStr[MAX_READER_MODE] =
{
	GENERATE_READER_MODE(GENERATE_ENUM_STR)
};

const CHARPTR DvrActionTypeStr[MAX_DVR_ACTION_TYPE] =
{
	GENERATE_DVR_ACTION_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR SmartRouteAccessTypStr[MAX_SMART_ROUTE_ACCESS_TYPE] =
{
	GENERATE_SMART_ROUTE_ACCESS_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR CardIdOrderStr[MAX_CARD_ID_ORDER_TYPE] =
{
	GENERATE_CARD_ID_ORDER(GENERATE_ENUM_STR)
};

const CHARPTR EnrollmentTypeStr[MAX_ENROLLMENT_TYPE] =
{
	GENERATE_ENROLLMENT_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR TemplatePerFingureStr[MAX_TEMPLATES_PER_FINGER] =
{
	GENERATE_TEMPLATES_PER_FINGER(GENERATE_ENUM_STR)
};

const CHARPTR AccessModeStr[MAX_ACCESS_MODE] =
{
	GENERATE_ACCESS_MODE(GENERATE_ENUM_STR)
};

const CHARPTR TwoPersonModeStr[MAX_TWO_PERSON_MODE] =
{
	GENERATE_TWO_PERSON_MODE(GENERATE_ENUM_STR)
};

const CHARPTR SmartRouteOrderTypeStr[MAX_SMART_ROUTE_ORDER] =
{
	GENERATE_SMART_ROUTE_ORDER_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR DvrUserEventTypeStr[MAX_DVR_EVENT_USER] =
{
	GENERATE_DVR_EVENT_USER_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR TimeFormatStr[MAX_TIME_FORMAT] =
{
	GENERATE_TIME_FORMAT(GENERATE_ENUM_STR)
};

const CHARPTR ZoneApplTypStr[MAX_ZONE_APPL] =
{
	GENERATE_ZONE_APPL(GENERATE_ENUM_STR)
};

const CHARPTR SenseTypStr[MAX_SENSE_TYPE] =
{
	GENERATE_SENSE_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR NtpModeStr[MAX_NTP_MODE] =
{
	GENERATE_NTP_MODE(GENERATE_ENUM_STR)
};

const CHARPTR ReaderTypeStr[MAX_READER_TYPE] =
{
	GENERATE_READER_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR UserTypStr[MAX_USER_TYPE] =
{
	GENERATE_CONFIG_USER_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR VamCardTypeStr[MAX_VAM_CARD_TYPE] =
{
	GENERATE_VAM_CARD_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR KeypadStr[MAX_KEYPAD]=
{
	GENERATE_KEYPAD(GENERATE_ENUM_STR)
};

const CHARPTR DoorLockTypeStr[MAX_DOOR_LOCK_TYPE]=
{
	GENERATE_DOOR_LOCK_TYPE(GENERATE_ENUM_STR)
};

const CHARPTR WPSTrigerTypeStr[MAX_WPS_TRIGER_TYP]=
{
	GENERATE_WPS_TRIGER_TYP(GENERATE_ENUM_STR)
};

const CHARPTR FprTemplateFormatStr[MAX_FINGER_TEMPLATE_FORMAT] =
{
	GENERATE_FPR_TEMPLATE_FORMAT(GENERATE_ENUM_STR)
};

const CHARPTR WiegandOutEventTypeStr[MAX_WIEGAND_EVENT_FORMAT] =
{
	GENERATE_WIEGAND_EVENT_FORMAT(GENERATE_ENUM_STR)
};

const CHARPTR WigandRedrModeStr[MAX_WIGND_RDR_MODE] =
{
	GENERATE_WIGND_RDR_MODE(GENERATE_ENUM_STR)
};

const CHARPTR WigandOutFormtStr[MAX_WIGND_OUT_FRMT] =
{
	GENERATE_WIGND_OUT_FRMT(GENERATE_ENUM_STR)
};

const CHARPTR WigandOutDirStr[MAX_WIGND_OUT_DIR] =
{
	GENERATE_WIGND_OUT_DIR(GENERATE_ENUM_STR)
};

const CHARPTR EnrollIdTypeStr[MAX_ENROLL_ID] =
{
	GENERATE_ENROLL_ID_TYPE(GENERATE_ENUM_STR)
};

//******** Static Variables **********

//******** Function Definations ******
