#if !defined MX_AV_RESP_H
#define MX_AV_RESP_H
///////////////////////////////////////////////////////////////////////////
//
//   MMM     MMM       AAA       TTTTTTTTTT  RRRRRR    IIIIIIII  XX   XX
//   MMMM   MMMM      AA AA          TT      RR   RR      II      XX XX
//   MM MM MM MM     AA   AA         TT      RR    RR     II       XXX
//   MM  MM   MM    AAAAAAAAA        TT      RRRRRRR      II       XXX
//   MM       MM   AA       AA       TT      RR  RR       II      XX XX
//   MM       MM  AA         AA      TT      RR   RR   IIIIIIII  XX   XX
//
//   Company      : Matrix Telecom Pvt. Ltd., Baroda, India.
//   Project      : ACS (Access Control System)
//   Created By   : Mukesh Savaliya
//   File         : MxAvResp.h
//   Description  : This file contains audio and visual related functions.
//
/////////////////////////////////////////////////////////////////////////////

#include "MxTypedef.h"
#include "MxConfig.h"
#include "MxSysTimer.h"
#include "MxSlaveMsg.h"
#include "MxEventLog.h"

//******** Defines and Data Types ****
#define LCD_IDLE_TIMER						3	// in seconds
#define READER_RESP_TIMER		 			6	// in seconds
#define BU_PROG_TIMER						10
#define FW_PROG_TIMER						6000 // 100 minute
#define LCD_IDLE_TIMER_ATNDC_SUMMARY_3SEC	3	// in seconds
#define LCD_IDLE_TIMER_ATNDC_SUMMARY_2SEC	2	// in seconds

typedef enum
{
	NORMAL_STATUS = 0,
	SPL_STATUS,
	LOCKED_STATUS,
	UNLOCKED_STATUS,
	MAX_STATUS
}STATUS_FIELD_e;

typedef enum
{
	NORMAL_MESSAGE = 0,
	SPL_MESSAGE,
	MENU_MESSAGE,
	MAX_MESSAGE
}MSG_FIELD_e;

#define GEN_USER_RESP_CMD_ENUM(USER_RESP_ENUM, USER_RESP_NAME) USER_RESP_ENUM,
#define GEN_USER_RESP_CMD_NAME(USER_RESP_ENUM, USER_RESP_NAME) USER_RESP_NAME,

#define USER_RESPONSE_CMD(API)\
		API(USER_RESP_IDLE,									ACCESS_IDLE_RESP)\
		API(USER_RESP_DISPLAY_IDLE_SCREEN,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_PROCESS,								ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_DISPLAY_GOING_IN_SCREEN,				ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_DISPLAY_GOING_OUT_SCREEN,				ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_DISPLAY_MENU_SCREEN,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_ACCESS_ALLOWED,						ACCESS_SUCCESS_RESP)\
		API(USER_RESP_ACCESS_EVENT_REGISTERED,				ACCESS_SUCCESS_RESP)\
		API(USER_RESP_ACCESS_DENIED,						ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_TIMEOUT,					ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_USER_BLOCKED,				ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_FIRST_IN,					ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_USER_DISABLED,			ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_INVALID_INPUT,			ACCESS_FAIL_RESP)\
		API(USER_RESP_AUTH_INVALID_ROUTE_INPUT,				ACCESS_FAIL_RESP)\
		API(USER_RESP_AUTH_INVALID_ROUTE_ACCESS,			ACCESS_FAIL_RESP)\
		API(USER_RESP_AUTH_DOOR_NOT_IN_ROUTE,				ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_CARD_READ_FAILED,			ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_INVALID_PIN,				ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_INVALID_FINGER,			ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_INVALID_FACE,				ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_INVALID_CARD,				ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_FP_MATCHING_TIMEOUT,		ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_NO_ACCESS,				ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_PASSBACK_HARD_VIOLATION,	ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_TWO_PERSON,				ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_OCCUPANCY_VIOLATION,		ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_DOOR_LOCK,				ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_AUTH_VALIDITY_EXPIRED,			ACCESS_FAIL_RESP)\
		API(USER_RESP_CARD_ENROLLED,						ACCESS_SUCCESS_RESP)\
		API(USER_RESP_FP_ENROLLED,							ACCESS_SUCCESS_RESP)\
		API(USER_RESP_ENROLL_FAIL,							ACCESS_FAIL_RESP)\
		API(USER_RESP_ENROLL_TIMEOUT,						ACCESS_FAIL_RESP)\
		API(USER_RESP_TIMEOUT,								ACCESS_FAIL_RESP)\
		API(USER_RESP_REMOVE_FINGER,						ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_FP_IDENTIFICATION_GLOBALLY, 			ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_MENU_FAILED,							ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_MENU_LOGIN_FAILED,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_PSWD_BLANK,							ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_PSWD_MISMATCH,						ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_PSWD_WRONG,							ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_PSWD_SUCCESS,							ACCESS_SUCCESS_RESP)\
		API(USER_RESP_SEARCHING_WIFI,						ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_WIFI_AP_NOT_FOUND,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_WRITING_CARD,							ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_CHANGING_CARD_KEY,					ACCESS_WAIT_RESP)\
		API(USER_RESP_SHOW_CARD,							ACCESS_WAIT_RESP)\
		API(USER_RESP_PLACE_FINGER,							ACCESS_WAIT_RESP)\
		API(USER_RESP_NEXT_CARD,							ACCESS_WAIT_RESP)\
		API(USER_RESP_NEXT_FINGER,							ACCESS_WAIT_RESP)\
		API(USER_RESP_NEXT_PERSON,							ACCESS_WAIT_RESP)\
		API(USER_RESP_SHOW_2ND_CREDENTIAL,					ACCESS_WAIT_RESP)\
		API(USER_RESP_SHOW_3RD_CREDENTIAL,					ACCESS_WAIT_RESP)\
		API(USER_RESP_GET_USER_INPUT,						ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_GET_USER_CREDENTIAL,					ACCESS_WAIT_RESP)\
		API(USER_RESP_USER_NOT_FOUND,						ACCESS_FAIL_RESP)\
		API(USER_RESP_ENROLL_USER_NOT_FOUND,				ACCESS_FAIL_RESP)\
		API(USER_RESP_USER_CRED_DELETED,					ACCESS_SUCCESS_RESP)\
		API(USER_RESP_SPL_FN_ACTIVATED,						ACCESS_SUCCESS_RESP)\
		API(USER_RESP_SPL_FN_INVALID,						ACCESS_FAIL_RESP)\
		API(USER_RESP_SPL_FN_IS_ACTIVE,						ACCESS_FAIL_RESP)\
		API(USER_RESP_ENROLLMENT_DISABLED,					ACCESS_FAIL_RESP)\
		API(USER_RESP_FUNCTION_DISABLED,					ACCESS_FAIL_RESP)\
		API(USER_RESP_VERIFY_SELECTION,						ACCESS_FAIL_RESP)\
		API(USER_RESP_VERIFY_READER,						ACCESS_FAIL_RESP)\
		API(USER_RESP_VERIFY_CARD_TYPE,						ACCESS_FAIL_RESP)\
		API(USER_RESP_CRED_LIMIT_EXCEEDS,					ACCESS_FAIL_RESP)\
		API(USER_RESP_DUPL_USER_CARD,						ACCESS_FAIL_RESP)\
		API(USER_RESP_DUPL_USER_SPL_FN_CARD,				ACCESS_FAIL_RESP)\
		API(USER_RESP_DUPL_USER_FINGER,						ACCESS_FAIL_RESP)\
		API(USER_RESP_READING_FROM_CARD,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_BUZ_AUDIO_IDLE,						ACCESS_IDLE_RESP)\
		API(USER_RESP_FP_MEM_FULL,							ACCESS_FAIL_RESP)\
		API(USER_RESP_PLACE_FINGER_AGAIN,					ACCESS_WAIT_RESP)\
		API(USER_RESP_ENTER_PIN,							ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_ENROLL_TRY_AGAIN_FINGER,				ACCESS_FAIL_RESP)\
		API(USER_RESP_FIRMWARE_UPLOAD_STATUS_SUCCESS,		ACCESS_SUCCESS_RESP)\
		API(USER_RESP_FIRMWARE_UPLOAD_STATUS_FAIL,			ACCESS_FAIL_RESP)\
		API(USER_RESP_BACKUP_UPDATE_PROGRESS,				ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_BACKUP_UPDATE_NO_EVENT,				ACCESS_FAIL_RESP)\
		API(USER_RESP_BACKUP_UPDATE_XFER_FAILED,			ACCESS_FAIL_RESP)\
		API(USER_RESP_BACKUP_UPDATE_XFER_SUCCESS,			ACCESS_SUCCESS_RESP)\
		API(USER_RESP_BACKUP_UPDATE_NO_MENORY,				ACCESS_FAIL_RESP)\
		API(USER_RESP_BACKUP_UPDATE_INVALID_DEVICE,			ACCESS_FAIL_RESP)\
		API(USER_RESP_BACKUP_UPDATE_FILE_NOT_FOUND,			ACCESS_FAIL_RESP)\
		API(USER_RESP_BACKUP_UPDATE_FW_FILE_NOT_FOUND,		ACCESS_FAIL_RESP)\
		API(USER_RESP_BACKUP_UPDATE_USB_NOT_FOUND,			ACCESS_FAIL_RESP)\
		API(USER_RESP_BACKUP_UPDATE_CHECKSUM_FAIL,			ACCESS_FAIL_RESP)\
		API(USER_RESP_BACKUP_UPDATE_DOWNGRAGE_CNTRL,		ACCESS_FAIL_RESP)\
		API(USER_RESP_USB_DISCONNECTED,						ACCESS_FAIL_RESP)\
		API(USER_RESP_USB_CONNECTED,						ACCESS_SUCCESS_RESP)\
		API(USER_RESP_USB_INVALID_FS,						ACCESS_FAIL_RESP)\
		API(USER_RESP_MMC_DEVICE_STATUS,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_ENTER_PASSWD,							ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_CAFE_ALLOW,							ACCESS_SUCCESS_RESP)\
		API(USER_RESP_CAFE_DENIED,							ACCESS_FAIL_RESP)\
		API(USER_RESP_CAFE_CARD_WRITE_FAILED,				ACCESS_FAIL_RESP)\
		API(USER_RESP_CAFE_SHOW_YOUR_ID,					ACCESS_WAIT_RESP)\
		API(USER_RESP_CAFE_SHOW_CARD,						ACCESS_WAIT_RESP)\
		API(USER_RESP_CAFE_CMD_SUCCESS,						ACCESS_SUCCESS_RESP)\
		API(USER_RESP_CAFE_CMD_FAIL,						ACCESS_FAIL_RESP)\
		API(USER_RESP_CAFE_CMD_TIMEOUT,						ACCESS_FAIL_RESP)\
		API(USER_RESP_CAFE_NOT_SERVING_NOW,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_PRINT_CMD_SENT,						ACCESS_SUCCESS_RESP)\
		API(USER_RESP_SYSTEM_DEFAULT,						ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_ROUTE_ACCESS_CARD_WRITE_FAILED,		ACCESS_FAIL_RESP)\
		API(USER_RESP_TOUCH_SCREEN_TEST_START,				ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_LCD_TEST_START,						ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_TEST_SUCCESS,							ACCESS_SUCCESS_RESP)\
		API(USER_RESP_TEST_FAIL,							ACCESS_FAIL_RESP)\
		API(USER_RESP_APPLY_FOUR_STATE_INPUT,				ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_WRONG_FOUR_STATE_INPUT,				ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_APPLY_TWO_STATE_INPUT,				ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_TWO_STATE_OUPUT,						ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_KEY_CHANGE_SHOW_CARD,					ACCESS_WAIT_RESP)\
		API(USER_RESP_KEY_CHANGE_SUCCESS,					ACCESS_SUCCESS_RESP)\
		API(USER_RESP_KEY_CHANGE_FAIL,						ACCESS_FAIL_RESP)\
		API(USER_RESP_WPS_PROCESSING,						ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_WIFI_CONNECTED,						ACCESS_SUCCESS_RESP)\
		API(USER_RESP_PASSWORD_DEFAULTED,					ACCESS_SUCCESS_RESP)\
		API(USER_RESP_PD_USER_ALLOWED,						ACCESS_ALLOWED_RESP)\
		API(USER_RESP_PD_USER_DENIED,						ACCESS_DENIED_RESP)\
		API(USER_RESP_PD_READING_CARD,						ACCESS_PROCESS_RESP)\
		API(USER_RESP_PD_PLACE_YOUR_FINGER,					ACCESS_WAIT_RESP)\
		API(USER_RESP_PD_INVALID_CARD,						ACCESS_DENIED_RESP)\
		API(USER_RESP_PD_CARD_READ_FAILED,					ACCESS_DENIED_RESP)\
		API(USER_RESP_PD_INVALID_PASSWORD,					ACCESS_DENIED_RESP)\
		API(USER_RESP_PD_MENU_TIMEOUT,						ACCESS_TIMEOUT_RESP)\
		API(USER_RESP_PD_SYSTEM_DEFAULTING,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_PD_SYSTEM_DEFAULTED,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_PD_FIRMWARE_UPLOAD_SUCCESS,			ACCESS_ALLOWED_RESP)\
		API(USER_RESP_PD_FIRMWARE_UPLOAD_FAIL,				ACCESS_DENIED_RESP)\
		API(USER_RESP_PD_COMMUNICATION_ERROR,				ACCESS_DENIED_RESP)\
		API(USER_RESP_PD_FIRMWARE_XFER_SUCCESS,				ACCESS_ALLOWED_RESP)\
		API(USER_RESP_PD_FIRMWARE_XFER_FAIL,				ACCESS_DENIED_RESP)\
		API(USER_RESP_PD_NO_WIFI_MODULE,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_PD_SEARCHING_WIFI,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_PD_WPS_PROCESSING,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_PD_WIFI_CONNECTED,					ACCESS_SUCCESS_RESP)\
		API(USER_RESP_OPEN_DOOR_WEB_API_COMMAND,			ACCESS_ALLOWED_RESP)\
		API(USER_RESP_SELF_ENROLL_REQ_INPUT,				ACCESS_WAIT_RESP)\
		API(USER_RESP_VAM_ACCESS_ALLOWED,					ACCESS_SUCCESS_RESP)\
		API(USER_RESP_VAM_SHOW_2ND_CREDENTIAL,				ACCESS_WAIT_RESP)\
		API(USER_RESP_VAM_SHOW_3RD_CREDENTIAL,				ACCESS_WAIT_RESP)\
		API(USER_RESP_VAM_DOOR_LOCK,						ACCESS_FAIL_RESP)\
		API(USER_RESP_VAM_VALIDITY_EXPIRED,					ACCESS_FAIL_RESP)\
		API(USER_RESP_VAM_CRED_INVALID_SEQ,					ACCESS_FAIL_RESP)\
		API(USER_RESP_VAM_INVALID_CARD,						ACCESS_FAIL_RESP)\
		API(USER_RESP_VAM_INVALID_SAMRT_ROUTE_ACCESS,		ACCESS_FAIL_RESP)\
		API(USER_RESP_VAM_INVALID_SMART_ROUTE_INPUT,		ACCESS_FAIL_RESP)\
		API(USER_RESP_VAM_SMART_ROUTE_CARD_WRITE_FAILED,	ACCESS_FAIL_RESP)\
		API(USER_RESP_VAM_NO_ACCESS,						ACCESS_FAIL_RESP)\
		API(USER_RESP_VISITOR_ACCESS_DENY,					ACCESS_FAIL_RESP)\
		API(USER_RESP_OCCUPANCY_WAIT_FOR_NEXT_USER,			ACCESS_WAIT_RESP)\
		API(USER_RESP_MIN_OCCUPANCY_IS_1,					ACCESS_FAIL_RESP)\
		API(USER_RESP_MIN_OCCUPANCY_IS_2,					ACCESS_FAIL_RESP)\
		API(USER_RESP_ACCESS_ALLOWED_WITH_JOBCODE,			ACCESS_SUCCESS_RESP)\
		API(USER_RESP_FAIL_TO_SEND_API_TO_SERVER,			ACCESS_FAIL_RESP)\
		API(USER_RESP_PROCESSING_QUERY,						ACCESS_WAIT_RESP)\
		API(USER_RESP_WAIT_FOR_SIGNAL,						ACCESS_WAIT_RESP)\
		API(USER_RESP_PLACE_FINGER_BIO_ONLY_MODE,			ACCESS_WAIT_RESP)\
		API(USER_RESP_SUCCESS_SCREEN,						ACCESS_SUCCESS_RESP)\
		API(USER_RESP_FAIL_SCREEN,							ACCESS_FAIL_RESP)\
		API(USER_RESP_READ_CARD_API,						ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_WRITE_CARD_API,						ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_SHOW_CARD_API,						ACCESS_WAIT_RESP)\
		API(MODE_NOT_SUPPORTED_SCREEN,						ACCESS_FAIL_RESP)\
		API(USER_RESP_WAIT_FOR_WGND_PIN,          			ACCESS_WAIT_RESP)\
		API(USER_RESP_PIN_CHANGED,							ACCESS_SUCCESS_RESP)\
		API(USER_RESP_PIN_EXISTS,							ACCESS_FAIL_RESP)\
		API(FTP_FIRMWARE_INITILIZE,							ACCESS_WAIT_RESP)\
		API(USER_RESP_NOT_PRESENT_ON_PANEL,					ACCESS_FAIL_RESP)\
		API(USER_RESP_DO_YOU_ASSIGN_USER_ON_DEVICE,			ACCESS_WAIT_RESP)\
		API(USER_RESP_DO_YOU_ADD_ASSIGN_USER_ON_DEVICE,		ACCESS_WAIT_RESP)\
		API(USER_RESP_ADD_USER_FAIL,						ACCESS_FAIL_RESP)\
		API(USER_RESP_ADD_USER_WAIT_TIME_OUT,				ACCESS_FAIL_RESP)\
		API(USER_RESP_NETWORK_ERROR,						ACCESS_FAIL_RESP)\
		API(USER_RESP_ATTENDANCE_DETAIL,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_TRANSACTION_WITHOUT_DISCOUNT,			ACCESS_WAIT_RESP)\
		API(USER_RESP_CAFE_POLICY_USER_DENIED,				ACCESS_FAIL_RESP)\
		API(USER_RESP_CAFE_CAFE_USERID_MISMATCH,			ACCESS_FAIL_RESP)\
		API(APPLY_LEAVE_RESPONSE,							ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_FAILED_TO_CONNECT_CAMERA,				ACCESS_FAIL_RESP)\
		API(USER_RESP_DENIED_FR_DISABLED,					ACCESS_FAIL_RESP)\
		API(USER_RESP_ACS_ENROLLED,							ACCESS_SUCCESS_RESP)\
		API(USER_RESP_ACS_ENROLLMENT_START_ON_DEVICE,		ACCESS_WAIT_RESP)\
		API(USER_RESP_TEMPERATURE_SENSOR_DISCONNECTED,		ACCESS_FAIL_RESP)\
		API(USER_RESP_TEMP_HARD_THRESHOLD_EXCEEDED,			ACCESS_FAIL_RESP)\
		API(USER_RESP_DETECTING_TEMPERATURE_SCREEN,			ACCESS_WAIT_RESP)\
		API(USER_RESP_MINIMUM_TEMP_RCVD,					ACCESS_FAIL_RESP)\
		API(USER_RESP_SHOW_PARTIAL_APPROACH_SCREEN,			ACCESS_WAIT_RESP)\
		API(USER_RESP_SHOW_FULL_APPROACH_SCREEN,			ACCESS_WAIT_RESP)\
		API(USER_RESP_AMBIENT_TEMPERATURE_CONFLICT,			ACCESS_FAIL_RESP)\
		API(USER_RESP_FACE_DELETE_FAILED,					ACCESS_FAIL_RESP)\
		API(USER_RESP_FACE_DELETE_PROCESSING,				ACCESS_WAIT_RESP)\
        API(USER_RESP_FACE_ENROLL_WAITING,					ACCESS_WAIT_RESP)\
		API(USER_RESP_FACE_ENROLL_PROCESSING,				ACCESS_WAIT_RESP)\
        API(USER_RESP_FACE_ENROLL_STOP,                     ACCESS_IDLE_RESP)\
		API(USER_RESP_DEVICE_BUSY,							ACCESS_FAIL_RESP)\
		API(USER_RESP_BENCHMARK_FW_FOUND,					ACCESS_FAIL_RESP)\
		API(USER_RESP_DENIED_FR_DISABLED_ON_DEVICE,			ACCESS_FAIL_RESP)\
		API(USER_RESP_DENIED_FACE_MASK_NOT_DETECTED,		ACCESS_FAIL_RESP)\
		API(USER_RESP_APPROACH_CAMERA,						ACCESS_WAIT_RESP)\
		API(USER_RESP_DISPLAY_IDLE_SCREEN_FOR_FR_STREAMING_IDLE_CAD,	ACCESS_IDLE_RESP)\
		API(USER_RESP_DISPLAY_IDLE_SCREEN_FOR_FR_STREAMING_WAIT_CAD,	ACCESS_WAIT_RESP)\
		API(USER_RESP_GUI_ABOUT_DEVICE_READERS_INTERFACES_SCREEN, ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_FACE_ENROLLED,						ACCESS_SUCCESS_RESP)\
		API(USER_RESP_PD_DA_USER_ALLOWED,					ACCESS_SUCCESS_RESP)\
		API(USER_RESP_PD_DA_USER_DENIED,					ACCESS_FAIL_RESP)\
		API(USER_RESP_PD_DA_PLACE_YOUR_FINGER,					ACCESS_WAIT_RESP)\
		API(USER_RESP_ADD_TEMP_USER_CONFIRMATION,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_ADD_TEMP_USER_NAME,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_TEMP_USER_REGISTERED_SUCCESSFULLY,			ACCESS_SUCCESS_RESP)\
		API(USER_RESP_TEMP_USER_PROCESSING,					ACCESS_CONTROL_RESP_MAX)\
		API(USER_RESP_TEMP_USER_FAILED_TO_CREATE,				ACCESS_FAIL_RESP)\
		API(USER_RESP_TEMP_USER_TIMEOUT,					ACCESS_FAIL_RESP)\
		API(USER_RESP_TEMP_USER_ABORTED,					ACCESS_FAIL_RESP)\
		API(USER_RESP_DEVICE_INACTIVE,                      			ACCESS_INACTIVE_DEVICE_RESP)\
		API(USER_RESP_ENTRY_RESTRICTED_DEVICE_INACTIVE,     			ACCESS_FAIL_RESP)\
        API(USER_RESP_MENU_LOGIN_RESTRICTED,					ACCESS_CONTROL_RESP_MAX)\

		

typedef enum
{
	USER_RESPONSE_CMD(GEN_USER_RESP_CMD_ENUM)
	MAX_USER_RESP
}USER_RESP_e;

typedef enum
{
	BUZ_LED_CAD_PORT,
	SPEAKER_CAD_PORT,
	MAX_CAD_PORT,
}CADENSE_SOUND_OUT_e;

//******** Function Prototypes *******
void DisplayIdleScreen(UINT32 dummy);
void SetAudioVisual(USER_RESP_e userResp, RESPONSE_PORT_e respPort, VOIDPTR dataPtr);
void SetBuzLedResp(USER_RESP_e userResp, RESPONSE_PORT_e respPort);
BOOL SetLcdIdleTimer(UINT16 timerValue);
BOOL SetLcdIdleTimerMilliSec(UINT16 timerValue);
void UpdateDisplayStatusField(void);
void SetNwStatusCad(COMM_PORT_e interface, UINT8 status);
void SendBuProgAvResp(BACKUP_UPDATE_TYPE_e buType, UINT8 percentage);
BOOL SetLCDDimTimer(void);
void SetLCDDimTimerTimeOut(UNUSED_PARA UINT32 dummy);
BOOL SetTemperatureIdleTimer(UINT16 timerValue);
void SetTemperatureTimerTimeOut(UNUSED_PARA UINT32 dummy);
VOID SetUserAllowEntryExitModeFlag(BOOL entryExitF);
BOOL GetUserAllowEntryExitModeFlag(VOID);
BOOL StatusBarExpanded(BOOL Status);
void StatusBarExpandedTimeout(UNUSED_PARA UINT32 dummy);
void ShowEntryRestrictedForDeviceInactive(void);
#endif  // MX_AV_RESP_H
